name: uxe_loft
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2

  # Firebase dependencies
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  google_sign_in: ^6.0.0

  intl_phone_field: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Added assets section
  assets:
    - lib/assets/images/onlinepayment.png
    - lib/assets/images/online_shopping.png
    - lib/assets/images/home_delivery.png
    - lib/assets/images/google_facebook.png
    - lib/assets/images/logo.png
    - lib/assets/images/Rectangle.png
    - lib/assets/images/logos.png
    - lib/assets/images/apple.png
    - lib/assets/images/google.png
    - lib/assets/images/facebook.png
    - lib/assets/images/next arrow.png
    - lib/assets/images/Skip__.png
    - lib/assets/images/multi_kit.png
    - lib/assets/images/lipstick.png
    - lib/assets/images/poster.png
    - lib/assets/images/beauty.png
    - lib/assets/images/offers.png
    - lib/assets/images/fashion.png
    - lib/assets/images/home.png
    - lib/assets/images/shirt.png
    - lib/assets/images/woman_bag.png
    - lib/assets/images/dress.png
    - lib/assets/images/mobiles.png
    - lib/assets/images/Devider.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"
