// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxFcMrWItAbMrzj9jH4jNSTDtheIeVDlg',
    appId: '1:223831215065:web:2087c71b8d5369685ce7c8',
    messagingSenderId: '223831215065',
    projectId: 'uxe-loft',
    authDomain: 'uxe-loft.firebaseapp.com',
    storageBucket: 'uxe-loft.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ--FlcOkL8oHGR6YU_sMJe4Ujd48bQME',
    appId: '1:223831215065:android:a57ca3adbd3339765ce7c8',
    messagingSenderId: '223831215065',
    projectId: 'uxe-loft',
    storageBucket: 'uxe-loft.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBODbrhjkirAYeFwilRv_MrCZnxgqYj3Ds',
    appId: '1:223831215065:ios:887453c8ecd026a65ce7c8',
    messagingSenderId: '223831215065',
    projectId: 'uxe-loft',
    storageBucket: 'uxe-loft.firebasestorage.app',
    iosBundleId: 'com.example.uxeLoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBODbrhjkirAYeFwilRv_MrCZnxgqYj3Ds',
    appId: '1:223831215065:ios:887453c8ecd026a65ce7c8',
    messagingSenderId: '223831215065',
    projectId: 'uxe-loft',
    storageBucket: 'uxe-loft.firebasestorage.app',
    iosBundleId: 'com.example.uxeLoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxFcMrWItAbMrzj9jH4jNSTDtheIeVDlg',
    appId: '1:223831215065:web:8cfad4e06a424fd85ce7c8',
    messagingSenderId: '223831215065',
    projectId: 'uxe-loft',
    authDomain: 'uxe-loft.firebaseapp.com',
    storageBucket: 'uxe-loft.firebasestorage.app',
  );
}
